const GRID = require('path').resolve(__dirname, '..');
const P=require(GRID + '/js/fuel/presets.js');
const eq=(n,a,b)=>{const ok=JSON.stringify(a)===JSON.stringify(b);console.log(ok?'ok':'FAIL',n,ok?'':JSON.stringify(a)+' != '+JSON.stringify(b));if(!ok)process.exitCode=1};
const p=P.parseQuickLog;
eq('S1',p('S1'),{code:'S1',qty:1,slot:null});
eq('2x S1',p('2x S1'),{code:'S1',qty:2,slot:null});
eq('s1 x2',p('s1 x2'),{code:'S1',qty:2,slot:null});
eq('S1 dinner',p('S1 dinner'),{code:'S1',qty:1,slot:'dinner'});
eq('dinner 2x s1',p('dinner 2x s1'),{code:'S1',qty:2,slot:'dinner'});
eq('1.5x B1 breakfast',p('1.5x B1 breakfast'),{code:'B1',qty:1.5,slot:'breakfast'});
eq('2 x S1',p('2 x S1'),{code:'S1',qty:2,slot:null});
eq('padded',p('  s1  '),{code:'S1',qty:1,slot:null});
eq('SHAKE',p('shake'),{code:'SHAKE',qty:1,slot:null});
eq('empty',p(''),null);
eq('only qty',p('2x'),null);
eq('too many',p('50x S1'),null);
eq('zero',p('0x S1'),null);
eq('garbage',p('s1 !!'),null);
eq('two codes',p('s1 s2'),null);
const presets=[{code:'S1',name:'Protein Bar'},{code:'S2',name:'Greek Yogurt'},{code:'SHAKE',name:'Post-workout Shake'},{code:'B1',name:'Oats'}];
eq('suggest s',P.suggest('s',presets).map(x=>x.code),['S1','S2','SHAKE']);
eq('suggest 2x s1',P.suggest('2x s1',presets).map(x=>x.code),['S1']);
eq('suggest name',P.suggest('oat',presets).map(x=>x.code),['B1']);
eq('scale',P.scale({calories:210,protein:20,carbs:22,fat:7},2),{calories:420,protein:40,carbs:44,fat:14});
eq('slot 8am',P.slotByHour(8),'breakfast'); eq('slot 22',P.slotByHour(22),'snack');
