const GRID = require('path').resolve(__dirname, '..');
const path = require('path'), R = GRID + '/grid-backend/';
const stub = (p, exports) => { const f = path.join(R, 'src', p); require.cache[f] = { id: f, filename: f, loaded: true, exports }; };
const calls = []; let photoCount = 0;
const tbl = (name) => new Proxy({}, { get: (_, m) => async (a) => { calls.push([name, m, a]); if (m === 'count') return photoCount; if (m === 'findMany') return name === 'healthDaily' ? [{ date: '2026-10-01', caloriesTotal: 2600 }] : []; if (m === 'findFirst') return a.where.id === 'mine' ? { id: 'mine' } : null; return { id: 'new', ...(a && (a.data || a.create) || {}) }; } });
stub('middleware/auth.js', { requireAuth: (req, res, next) => { req.user = { id: 'u1' }; next(); } });
stub('lib/db.js', new Proxy({}, { get: (_, n) => tbl(n) }));
const express = require(R + 'node_modules/express'); const app = express(); app.use(express.json({ limit: '1mb' })); app.use('/api/progress', require(R + 'src/routes/progress'));
const t = (n, ok, x) => { console.log(ok ? 'ok  ' : 'FAIL', n, ok ? '' : x); if (!ok) process.exitCode = 1; };
const JPG = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBD' + 'A'.repeat(200);
const srv = app.listen(4014, async () => {
  const j = (p, m, b) => fetch('http://localhost:4014' + p, { method: m, headers: { 'Content-Type': 'application/json' }, body: b ? JSON.stringify(b) : undefined }).then(async r => [r.status, await r.json().catch(() => ({}))]);
  const ok = { date: '2026-10-05', image: JPG, thumb: JPG, weightKg: 72.4, note: 'week 4' };
  let r;
  r = await j('/api/progress/photos', 'POST', ok); t('valid jpeg accepted', r[0] === 201 && calls.at(-1)[2].data.userId === 'u1', JSON.stringify(r));
  r = await j('/api/progress/photos', 'POST', { ...ok, image: 'data:image/png;base64,iVBORw0KGgo=' }); t('png rejected', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, image: 'data:image/jpeg;base64,' + Buffer.from('<script>alert(1)</script>').toString('base64') }); t('non-jpeg bytes disguised as jpeg rejected (magic bytes)', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, image: 'data:text/html;base64,/9j/4AAQ' }); t('html data url rejected', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, image: JPG + 'A'.repeat(760000) }); t('oversized image rejected', r[0] === 400 || r[0] === 413);
  r = await j('/api/progress/photos', 'POST', { ...ok, thumb: JPG + 'A'.repeat(70000) }); t('oversized thumb rejected', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, date: 'yesterday' }); t('bad date rejected', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, weightKg: 5 }); t('absurd weight rejected', r[0] === 400);
  r = await j('/api/progress/photos', 'POST', { ...ok, userId: 'attacker' }); t('client cannot set userId', r[0] === 201 && calls.at(-1)[2].data.userId === 'u1');
  photoCount = 400; r = await j('/api/progress/photos', 'POST', ok); t('photo cap enforced', r[0] === 409); photoCount = 0;
  r = await j('/api/progress/photos/other', 'GET'); t("someone else's photo -> 404", r[0] === 404);
  r = await j('/api/progress/photos/mine', 'GET'); t('own photo readable', r[0] === 200);
  r = await j('/api/progress/photos/other', 'DELETE'); t("cannot delete someone else's photo", r[0] === 404);
  r = await j('/api/progress/photos', 'GET'); t('list returns 200', r[0] === 200 && calls.some(c => c[1] === 'findMany' && c[2].select && c[2].select.thumb && !c[2].select.image), 'list must not select full image');
  r = await j('/api/progress/weight/2026-10-05', 'PUT', { kg: 72.4 }); t('weight upsert', r[0] === 200);
  r = await j('/api/progress/weight/2026-10-05', 'PUT', { kg: 500 }); t('weight 500 rejected', r[0] === 400);
  r = await j('/api/progress/weight/xx', 'PUT', { kg: 72 }); t('weight bad date', r[0] === 400);
  r = await j('/api/progress/weight?from=bad', 'GET'); t('weight bad range', r[0] === 400);
  // calories burned (typed in by hand)
  r = await j('/api/progress/burn/2026-10-05', 'PUT', { kcal: 2650 }); t('burn upsert ok, stored as manual', r[0] === 200 && r[1].kcal === 2650 && calls.some(c => c[0] === 'healthDaily' && c[1] === 'upsert' && c[2].create.source === 'manual' && c[2].create.caloriesTotal === 2650 && c[2].create.userId === 'u1'));
  r = await j('/api/progress/burn/2026-10-05', 'PUT', { kcal: 100 }); t('burn under 500 rejected', r[0] === 400);
  r = await j('/api/progress/burn/2026-10-05', 'PUT', { kcal: 50000 }); t('burn over 12000 rejected', r[0] === 400);
  r = await j('/api/progress/burn/2026-10-05', 'PUT', { kcal: 2650.5 }); t('fractional burn rejected', r[0] === 400);
  r = await j('/api/progress/burn/2026-10-05', 'PUT', { kcal: '2650' }); t('string burn rejected', r[0] === 400);
  r = await j('/api/progress/burn/tomorrow', 'PUT', { kcal: 2650 }); t('burn bad date rejected', r[0] === 400);
  r = await j('/api/progress/burn?from=2026-10-01', 'GET'); t('burn list returns {date,kcal}', r[0] === 200 && r[1][0].kcal === 2600 && r[1][0].date === '2026-10-01' && !('caloriesTotal' in r[1][0]));
  r = await j('/api/progress/burn?to=nope', 'GET'); t('burn list bad range rejected', r[0] === 400);
  r = await j('/api/progress/burn/2026-10-05', 'DELETE'); t('burn delete only nulls the field for this user', r[0] === 200 && calls.some(c => c[0] === 'healthDaily' && c[1] === 'updateMany' && c[2].where.userId === 'u1' && c[2].data.caloriesTotal === null));
  srv.close();
});
